num_batches: 10
batch_size: 8
lr: 0.001
num_epochs: 60
min_val: 0
max_val: 100
model_name: "openai-community/gpt2-large"
shl: True
model_path: "./chk/alignment_number2number/trained_numeric_lm.pth"
num_batches: 50
batch_size: 8
lr: 0.003
savestage2: "./chk/alignment_txt2number/alignment_text2n_lm.pth"
